language: android
jdk: oraclejdk7
before_script:
 - chmod +x gradlew
android:
    components:
        - build-tools-22.0.1
        - android-22
        - android-19
        - android-16
        - android-14
        - android-11
        - android-8
        - platform-tools
        - extra-android-support
        - extra-android-m2repository
    licenses:
        - 'android-sdk-license-.+'